services:
  - type: web
    name: lead-scoring-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn lead_scoring_api:app --host 0.0.0.0 --port 8000
